<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class EmployeeSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('employees')->insert([
            // Unit Personnel
            [
                'name' => 'Meranda',
                'email' => 'randa@gmail.com',
                'username' => 'randa',
                'gender' => 'Wanita',
                'address' => 'Jl. Mawar No. 12, Jakarta',
                'phone_number' => '081234567890',
                'division' => 'Unit Personnel',
                'email_verified_at' => Carbon::now(),
                'password' => Hash::make('foobarrr'),
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Ayu Lestari',
                'email' => 'ayu@gmail.com',
                'username' => 'ayu',
                'gender' => 'Wanita',
                'address' => 'Jl. Kenanga No. 5, Jakarta',
                'phone_number' => '081234567891',
                'division' => 'Unit Personnel',
                'email_verified_at' => Carbon::now(),
                'password' => Hash::make('foobarrr'),
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Dewi Sartika',
                'email' => 'dewi@gmail.com',
                'username' => 'dewis',
                'gender' => 'Wanita',
                'address' => 'Jl. Anggrek No. 9, Jakarta',
                'phone_number' => '081234567892',
                'division' => 'Unit Personnel',
                'email_verified_at' => Carbon::now(),
                'password' => Hash::make('foobarrr'),
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Bagus Prasetyo',
                'email' => 'bagus@gmail.com',
                'username' => 'bagus',
                'gender' => 'Pria',
                'address' => 'Jl. Dahlia No. 3, Jakarta',
                'phone_number' => '081234567893',
                'division' => 'Unit Personnel',
                'email_verified_at' => Carbon::now(),
                'password' => Hash::make('foobarrr'),
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Lina Wijaya',
                'email' => 'lina@gmail.com',
                'username' => 'lina',
                'gender' => 'Wanita',
                'address' => 'Jl. Flamboyan No. 7, Jakarta',
                'phone_number' => '081234567894',
                'division' => 'Unit Personnel',
                'email_verified_at' => Carbon::now(),
                'password' => Hash::make('foobarrr'),
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // WTP Personnel
            [
                'name' => 'Andi Saputra',
                'email' => 'andi@gmail.com',
                'username' => 'andis',
                'gender' => 'Pria',
                'address' => 'Jl. Melati No. 21, Bandung',
                'phone_number' => '082198765432',
                'division' => 'WTP Personnel',
                'email_verified_at' => Carbon::now(),
                'password' => Hash::make('foobarrr'),
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Rina Amelia',
                'email' => 'rina@gmail.com',
                'username' => 'rina',
                'gender' => 'Wanita',
                'address' => 'Jl. Mawar No. 10, Bandung',
                'phone_number' => '082198765433',
                'division' => 'WTP Personnel',
                'email_verified_at' => Carbon::now(),
                'password' => Hash::make('foobarrr'),
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Dimas Raka',
                'email' => 'dimas@gmail.com',
                'username' => 'dimas',
                'gender' => 'Pria',
                'address' => 'Jl. Teratai No. 22, Bandung',
                'phone_number' => '082198765434',
                'division' => 'WTP Personnel',
                'email_verified_at' => Carbon::now(),
                'password' => Hash::make('foobarrr'),
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Nur Aini',
                'email' => 'aini@gmail.com',
                'username' => 'aini',
                'gender' => 'Wanita',
                'address' => 'Jl. Anggrek No. 30, Bandung',
                'phone_number' => '082198765435',
                'division' => 'WTP Personnel',
                'email_verified_at' => Carbon::now(),
                'password' => Hash::make('foobarrr'),
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Fajar Sidik',
                'email' => 'fajar@gmail.com',
                'username' => 'fajar',
                'gender' => 'Pria',
                'address' => 'Jl. Cempaka No. 15, Bandung',
                'phone_number' => '082198765436',
                'division' => 'WTP Personnel',
                'email_verified_at' => Carbon::now(),
                'password' => Hash::make('foobarrr'),
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Ash FGD Personnel
            [
                'name' => 'Rudi Pandjaitan',
                'email' => 'rudi@gmail.com',
                'username' => 'rudi',
                'gender' => 'Pria',
                'address' => 'Jl. Soekarno No. 2, Yogyakarta',
                'phone_number' => '082198765437',
                'division' => 'Ash FGD Personnel',
                'email_verified_at' => Carbon::now(),
                'password' => Hash::make('foobarrr'),
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Tika Lestari',
                'email' => 'tika@gmail.com',
                'username' => 'tika',
                'gender' => 'Wanita',
                'address' => 'Jl. Merpati No. 6, Yogyakarta',
                'phone_number' => '082198765438',
                'division' => 'Ash FGD Personnel',
                'email_verified_at' => Carbon::now(),
                'password' => Hash::make('foobarrr'),
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Ardi Prabowo',
                'email' => 'ardi@gmail.com',
                'username' => 'ardi',
                'gender' => 'Pria',
                'address' => 'Jl. Rajawali No. 18, Yogyakarta',
                'phone_number' => '082198765439',
                'division' => 'Ash FGD Personnel',
                'email_verified_at' => Carbon::now(),
                'password' => Hash::make('foobarrr'),
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Sarah Maulida',
                'email' => 'sarah@gmail.com',
                'username' => 'sarah',
                'gender' => 'Wanita',
                'address' => 'Jl. Kutilang No. 4, Yogyakarta',
                'phone_number' => '082198765440',
                'division' => 'Ash FGD Personnel',
                'email_verified_at' => Carbon::now(),
                'password' => Hash::make('foobarrr'),
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Fikri Ramadhan',
                'email' => 'fikri@gmail.com',
                'username' => 'fikri',
                'gender' => 'Pria',
                'address' => 'Jl. Merapi No. 27, Yogyakarta',
                'phone_number' => '082198765441',
                'division' => 'Ash FGD Personnel',
                'email_verified_at' => Carbon::now(),
                'password' => Hash::make('foobarrr'),
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ]
        ]);
    }
}
